name: Audit project
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run cargo audit fix
        uses: simonhyll/cargo-audit@v1
