name: Rust

on:
  merge_group:
  pull_request:
    branches:
      - main
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Formatting
      run: cargo fmt --all -- --check
    - name: Add Clippy
      run: rustup component add clippy
    - name: Run Clippy
      run: cargo clippy -- -D warnings
